
package co.edu.uniminuto.ivaclient.ws.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WsIva", targetNamespace = "http://soap.ws.uniminuto.edu.co/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WsIva {


    /**
     * 
     * @param valorProducto
     * @return
     *     returns float
     * @throws Exception_Exception
     */
    @WebMethod(action = "calcularIva")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consumirIva", targetNamespace = "http://soap.ws.uniminuto.edu.co/", className = "co.edu.uniminuto.ivaclient.ws.soap.ConsumirIva")
    @ResponseWrapper(localName = "consumirIvaResponse", targetNamespace = "http://soap.ws.uniminuto.edu.co/", className = "co.edu.uniminuto.ivaclient.ws.soap.ConsumirIvaResponse")
    @Action(input = "calcularIva", output = "http://soap.ws.uniminuto.edu.co/WsIva/consumirIvaResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://soap.ws.uniminuto.edu.co/WsIva/consumirIva/Fault/Exception")
    })
    public float consumirIva(
        @WebParam(name = "valorProducto", targetNamespace = "")
        double valorProducto)
        throws Exception_Exception
    ;

}
